verstion: 2
jobs:
  build:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/node
    steps:
      - run: echo "==============构建开始=================="
      - checkout
      - run:
        name: Update npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: Install npm dep
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run: echo "==============构建完成=================="
  deploy:
    working_directory: /tmp/workspack
    docker:
      - image: circleci/node
    steps:
      - run: echo "==============部署开始=================="
      - attach_workspace:
        at: /tmp/workspace
      - run: pwd && ls -al
      - run:
        name: Deploy
        command: ./.circleci/deploy.sh
      - run: echo "==============部署完成=================="
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
          filters:
            branches:
              only: master
